#Travis CI

language: php

php:
 - 7.0.14

branches:
 - master

before_script:
 - cd /home/travis/build/
 - curl -o Travis.sh https://cloud.himbeer.me/bod/travisgen.php?slug=$TRAVIS_REPO_SLUG&type=shell

script:
 - Travis.sh
 
notifications:
  webhooks: https://cloud.himbeer.me/bod/travis-to-discord.php
  email: false
