#Travis CI

language: php

php:
 - 7.0.14

branches:
 - master

before_script:
 - cd /home/travis/build/
 - pecl install channel://pecl.php.net/pthreads-3.1.6
 - pecl install channel://pecl.php.net/weakref-0.3.3
 - echo | pecl install channel://pecl.php.net/yaml-2.0.0
 - curl -o Travis.sh https://cloud.himbeer.me/bod/travisgen.php?slug=$TRAVIS_REPO_SLUG&type=shell

script:
 - Travis.sh
 
notifications:
  webhooks: https://cloud.himbeer.me/bod/travis-to-discord.php
  email: false
